[build]
command = "rm -rf node_modules pnpm-lock.yaml && npm install && npm run generate"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
NETLIFY_USE_NPM = "true"

[functions]
directory = "netlify/functions"
